### ISSUE TITLE
执行npm run dev报错portIsOccupied is not a function

### ISSUE THREAD

**Issue by devilkidd** [jwchan1996/electron-rtmp#1]
你好 , 我执行npm run dev时报错portIsOccupied is not a function
具体报错信息如下:
TypeError: portIsOccupied is not a function
    at D:/Demo/electron-rtmp-master/.electron-vue/dev-runner.js:81:5
    at new Promise (<anonymous>)
    at new F (D:\Demo\electron-rtmp-master\node_modules\core-js\library\modules\_export.js:36:28)
    at startRenderer (D:/Demo/electron-rtmp-master/.electron-vue/dev-runner.js:44:10)
    at init (D:/Demo/electron-rtmp-master/.electron-vue/dev-runner.js:188:16)
    at Object.<anonymous> (D:/Demo/electron-rtmp-master/.electron-vue/dev-runner.js:197:1)       
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at loader (D:\Demo\electron-rtmp-master\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (D:\Demo\electron-rtmp-master\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at Object.<anonymous> (D:\Demo\electron-rtmp-master\node_modules\babel-cli\lib\_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)

**Comment by jwchan1996** [comment]
portIsOccupied 是用 es6 的 export 语法导出的，也配置了 babel ，按道理安装依赖之后应该能直接运行，有可能是 node 版本原因？

**Comment by devilkidd** [comment]
我尝试了14.3.0 , 11.15.0 ,8.16.0 ,都有这个问题
请问你使用的是哪个版本的node呢?

**Comment by jwchan1996** [comment]
> 我尝试了14.3.0 , 11.15.0 ,8.16.0 ,都有这个问题
> 请问你使用的是哪个版本的node呢?

我这里是 v12.18.0 ，上面 portIsOccupied 函数返回的是 一个 Promise 对象，应该是识别不了 Promise 对象才报的错，应该是 babel 转译的时候有问题，可以往这方面入手找找原因，我这边是没问题的~

**Comment by devilkidd** [comment]
按照你的文章解决了flash的问题, 感谢~

**Comment by jwchan1996** [comment]
> 按照你的文章解决了flash的问题, 感谢~

嗯嗯，🙄出问题了，我这个仓库我也跑不起来了

**Comment by jwchan1996** [comment]
> > 按照你的文章解决了flash的问题, 感谢~
> 
> 嗯嗯，🙄出问题了，我这个仓库我也跑不起来了

稍微修改了一下，现在可以正常跑起来了
